export const DEMO_MATS = [
      {id:'EST-P01',cat:'ESTRUCTURA',name:'M-01 Panel Frontal (con puerta)',brand:'IMEL',unit:'KG',cost:2095,baseQty:16.9,pres:'kg'},
      {id:'EST-P02',cat:'ESTRUCTURA',name:'M-02 Panel Izquierdo',brand:'IMEL',unit:'KG',cost:2095,baseQty:19.1,pres:'kg'},
      {id:'EST-P03',cat:'ESTRUCTURA',name:'M-03 Panel Posterior',brand:'IMEL',unit:'KG',cost:2095,baseQty:22.9,pres:'kg'},
      {id:'EST-P04',cat:'ESTRUCTURA',name:'M-04 Panel Derecho',brand:'IMEL',unit:'KG',cost:2095,baseQty:11.4,pres:'kg'},
      {id:'EST-P05',cat:'ESTRUCTURA',name:'M-05 Parrilla Cielo',brand:'IMEL',unit:'KG',cost:2095,baseQty:21.4,pres:'kg'},
      {id:'EST-P06',cat:'ESTRUCTURA',name:'M-06 Faldón Tina',brand:'IMEL',unit:'KG',cost:2095,baseQty:3.8,pres:'kg'},
      {id:'EST-CA40',cat:'ESTRUCTURA',name:'Montante Estructural CA 2x2x0,85mm (pre-dimensión)',brand:'IMEL',unit:'UNIDAD',cost:1702,baseQty:0.25,pres:'Barra 6m'},
      {id:'EST-U42',cat:'ESTRUCTURA',name:'Canal Estructural U 2x2x0,85mm (6m)',brand:'IMEL',unit:'UNIDAD',cost:3410,baseQty:0.7,pres:'Barra 6m'},
      {id:'EST-U153',cat:'ESTRUCTURA',name:'Canal Estructural U 2x6x0,85mm (6m)',brand:'IMEL',unit:'UNIDAD',cost:8349,baseQty:0.5,pres:'Barra 6m'},
      {id:'EST-FLEJE',cat:'ESTRUCTURA',name:'Arriostramiento Fleje 50x0,85mm',brand:'IMEL',unit:'MT',cost:370,baseQty:30,pres:'Rollo'},
      {id:'EST-G01',cat:'ESTRUCTURA',name:'Placa Gusset_01 Galvanizado 1mm',brand:'LASERCUT',unit:'UNIDAD',cost:2567,baseQty:2,pres:'Pieza'},
      {id:'EST-G03',cat:'ESTRUCTURA',name:'Placa Gusset_03 ESQ Galvanizado 1mm',brand:'LASERCUT',unit:'UNIDAD',cost:3009,baseQty:7,pres:'Pieza'},
      {id:'EST-G05',cat:'ESTRUCTURA',name:'Placa Gusset_05 ESQ Galvanizado 1mm',brand:'LASERCUT',unit:'UNIDAD',cost:3009,baseQty:1,pres:'Pieza'},
      {id:'EST-IZQIZJ',cat:'ESTRUCTURA',name:'Placa Externa Izaje IZQ Acero Carbono 3mm',brand:'LASERCUT',unit:'UNIDAD',cost:7035,baseQty:2,pres:'fijo'},
      {id:'EST-DERIZJ',cat:'ESTRUCTURA',name:'Placa Externa Izaje DER Acero Carbono 3mm',brand:'LASERCUT',unit:'UNIDAD',cost:7031,baseQty:2,pres:'fijo'},
      {id:'EST-ANGTENS',cat:'ESTRUCTURA',name:'Ángulo Tensor 40x40 L=70mm',brand:'STEELFIX',unit:'UNIDAD',cost:879,baseQty:6,pres:'Pieza'},
      {id:'EST-TLENT',cat:'ESTRUCTURA',name:'Tornillo Lenteja 8-18 x 1/2" (ensamble general)',brand:'STEELFIX',unit:'UNIDAD',cost:9.89,baseQty:1050,pres:'Unidad'},
      {id:'EST-THEX',cat:'ESTRUCTURA',name:'Tornillo Hexagonal 10-16 x 3/4" (fijación base+cielo)',brand:'STEELFIX',unit:'UNIDAD',cost:47,baseQty:250,pres:'Unidad'},
      {id:'EST-TAPE',cat:'ESTRUCTURA',name:'Max Tape 10x6mm (Rollo 10m)',unit:'UNIDAD',cost:11700,baseQty:0.5,pres:'Rollo 10m'},
      {id:'EST-TLENT1',cat:'ESTRUCTURA',name:'Tornillo Lenteja 8-18 x 1" (pilares compuestos)',brand:'STEELFIX',unit:'UNIDAD',cost:15,baseQty:100,pres:'Unidad'},
      {id:'BASE-TARIMA',cat:'BASE',name:'Tarima Base POD (placa estructural)',brand:'APPSA',unit:'MT2',cost:155000,baseQty:3.52,pres:'MT2'},
      {id:'POD_022',cat:'PUERTAS',name:'LISTON IMPREGNADO CEPILLADO 1 1/2 X 2¨',brand:'LIFEWOOD',unit:'UNIDAD',cost:2190.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_023',cat:'TECHO',name:'TERCIADO ESTRUCTURAL 1220 x 2440 x 9mm',brand:'CONSTRUPLAZA',unit:'UNIDAD',cost:16648.0,baseQty:1.3,pres:'Plancha 1220x2440mm'},
      {id:'CRI1988',cat:'ELECTRICO',name:'Tubo conduit C-IV 20 mm x 6 mt',brand:'S',unit:'UNIDAD',cost:1085.71,baseQty:0.5,pres:'Tubo 6m'},
      {id:'CRI305',cat:'ELECTRICO',name:'TUBO CONDUIT FLEXIBLE 20 mm (ROLLO 10 m)',brand:'S',unit:'MT',cost:790.0,baseQty:0.15,pres:'Rollo 10m'},
      {id:'CEL042',cat:'ELECTRICO',name:'CAJA DISTRIBUCION TABIQUE NARANJA 16-20mm',brand:'S',unit:'UNIDAD',cost:690.0,baseQty:5.0,pres:'Unidad'},
      {id:'CEL081',cat:'ELECTRICO',name:'SALIDA DE CAJA PVC CONDUIT 20 mm',brand:'S',unit:'UNIDAD',cost:120.0,baseQty:12.0,pres:'Unidad'},
      {id:'POD_029',cat:'ELECTRICO',name:'PLACA CIEGA S12 BLANCO',brand:'DARTEL',unit:'UNIDAD',cost:402.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_030',cat:'ELECTRICO',name:'PLACA INTERRUPTOR 9/12 1M SIMPLE S12 BLANCO',brand:'DARTEL',unit:'UNIDAD',cost:1006.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_031',cat:'ELECTRICO',name:'PLACA TOMACORRIENTE 10A DOBLE S12 BLANCO',brand:'DARTEL',unit:'UNIDAD',cost:1578.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_032',cat:'ELECTRICO',name:'Tortuga ovalada de aluminio IP-44 con rejilla blanca E-27 c/ampolleta led',unit:'UNIDAD',cost:4040.0,baseQty:1.0,pres:'Unidad'},
      {id:'7359861',cat:'ELECTRICO',name:'Curva PVC conduit C-III 20 mm',brand:'S',unit:'UNIDAD',cost:110.0,baseQty:7.0,pres:'Unidad'},
      {id:'POD_034',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 1,5 mm2 100 m Blanco',brand:'S',unit:'UNIDAD',cost:22530.0,baseQty:0.04,pres:'Rollo 100m'},
      {id:'POD_035',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 1,5 mm2 100 m Rojo',brand:'S',unit:'UNIDAD',cost:22530.0,baseQty:0.12,pres:'Rollo 100m'},
      {id:'POD_036',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 1,5 mm2 100 m Verde',brand:'S',unit:'UNIDAD',cost:22530.0,baseQty:0.04,pres:'Rollo 100m'},
      {id:'POD_037',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 2,5 mm2 100 m Blanco',brand:'S',unit:'UNIDAD',cost:36300.0,baseQty:0.3,pres:'Rollo 100m'},
      {id:'POD_038',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 2,5 mm2 100 m rojo',brand:'S',unit:'UNIDAD',cost:36300.0,baseQty:0.3,pres:'Rollo 100m'},
      {id:'POD_039',cat:'ELECTRICO',name:'Alambre de cobre aislado (H07V-U) 2,5 mm2 100 m Verde',brand:'S',unit:'UNIDAD',cost:36300.0,baseQty:0.3,pres:'Rollo 100m'},
      {id:'CRI2115',cat:'SANITARIO - AGUA POTABLE',name:'Tubo PN-16 PP RCT BETA  20 mmx3 m S.3.2',brand:'S',unit:'UNIDAD',cost:2290.0,baseQty:1.0,pres:'Tubo 3m'},
      {id:'POD_041',cat:'SANITARIO - AGUA POTABLE',name:'Tubo PN-12,5 PP RCT BETA 20 mm x3 m  S4',brand:'S',unit:'UNIDAD',cost:2290.0,baseQty:1.0,pres:'Tubo 3m'},
      {id:'CRI2116',cat:'SANITARIO - AGUA POTABLE',name:'Codo Transicion 90° PPR Gris 20 mm x1/2\" HE',brand:'S',unit:'UNIDAD',cost:2490.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2117',cat:'SANITARIO - AGUA POTABLE',name:'Codo Transicion 90° PPR Gris 20 mm x1/2\" HI',brand:'S',unit:'UNIDAD',cost:1690.0,baseQty:3.0,pres:'Unidad'},
      {id:'CRI2118',cat:'SANITARIO - AGUA POTABLE',name:'Codo PPR 90° 20 mm. Gris',brand:'S',unit:'UNIDAD',cost:210.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2120',cat:'SANITARIO - AGUA POTABLE',name:'Pasatubo PPR Puente 20 mm',brand:'S',unit:'UNIDAD',cost:940.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_046',cat:'SANITARIO - AGUA POTABLE',name:'Llave De Paso Cromada PPR 25 mm Vástago 2,3 cm',brand:'S',unit:'UNIDAD',cost:8990.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_047',cat:'SANITARIO - AGUA POTABLE',name:'Abrazadera PPR Gris 20 mm',brand:'S',unit:'UNIDAD',cost:190.0,baseQty:10.0,pres:'Unidad'},
      {id:'POD_048',cat:'SANITARIO - AGUA POTABLE',name:'Copla Fusión PPR 20 mm',brand:'S',unit:'UNIDAD',cost:130.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2121',cat:'SANITARIO - AGUA POTABLE',name:'Tubo PN-16 Gris PP RCT BETA 25 mm x3 m S.3.2',brand:'S',unit:'UNIDAD',cost:3490.0,baseQty:1.0,pres:'Tubo 3m'},
      {id:'POD_050',cat:'SANITARIO - AGUA POTABLE',name:'Tubo PN-12,5 Gris PP RCT BETA 25 mm x3 m S4',brand:'S',unit:'UNIDAD',cost:3490.0,baseQty:1.0,pres:'Tubo 3m'},
      {id:'POD_051',cat:'SANITARIO - AGUA POTABLE',name:'Tee  PPR 25X25X20',brand:'S',unit:'UNIDAD',cost:690.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2232',cat:'SANITARIO - AGUA POTABLE',name:'Tee PPR 25X20X25 mm Gris',brand:'S',unit:'UNIDAD',cost:990.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_053',cat:'SANITARIO - AGUA POTABLE',name:'Codo PPR 90° 25 mm. Gris',brand:'HOFFENS',unit:'UNIDAD',cost:290.0,baseQty:8.0,pres:'Unidad'},
      {id:'CRI1091',cat:'SANITARIO - AGUA POTABLE',name:'Copla Reducción PPR 25 X 20 mm',brand:'S',unit:'UNIDAD',cost:180.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2125',cat:'SANITARIO - AGUA POTABLE',name:'Abrazadera PPR Gris 25 mm',brand:'S',unit:'UNIDAD',cost:250.0,baseQty:6.0,pres:'Unidad'},
      {id:'POD_056',cat:'SANITARIO - AGUA POTABLE',name:'Copla Fusión PPR 25 mm',brand:'S',unit:'UNIDAD',cost:190.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2126',cat:'SANITARIO - AGUA POTABLE',name:'Llave Angular Cromada 1/2\"x1/2\" He He',brand:'S',unit:'UNIDAD',cost:7090.0,baseQty:1.0,pres:'Unidad'},
      {id:'CRI680_56',cat:'SANITARIO - INSUMO',name:'MAX TAPE 40X3mm (ROLLO 10M)',unit:'UNIDAD',cost:11700.0,baseQty:0.2,pres:'Rollo 10m'},
      {id:'POD_059',cat:'SANITARIO - ALCANTARILLADO',name:'TTEE  110 X 110 mm Bco c/goma',brand:'HOFFENS',unit:'UNIDAD',cost:8790.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_060',cat:'SANITARIO - ALCANTARILLADO',name:'CODO 45°  110 mm Bco c/goma',brand:'HOFFENS',unit:'UNIDAD',cost:8790.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_061',cat:'SANITARIO - ALCANTARILLADO',name:'REDUCCION 110 X 50 mm Bco c/goma',brand:'HOFFENS',unit:'UNIDAD',cost:6490.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_062',cat:'SANITARIO - ALCANTARILLADO',name:'REDUCCION 50 X 40 mm Bco c/goma',brand:'HOFFENS',unit:'UNIDAD',cost:1590.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI1868',cat:'SANITARIO - ALCANTARILLADO',name:'Copla PVC-S Bco c/goma 110mm Blanco',brand:'S',unit:'UNIDAD',cost:1610.0,baseQty:1.0,pres:'Unidad'},
      {id:'CRI2134',cat:'SANITARIO - ALCANTARILLADO',name:'Abrazadera PVC-S 110mm Gris',brand:'S',unit:'UNIDAD',cost:1690.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2175',cat:'SANITARIO - ALCANTARILLADO',name:'Tubo Blanco PVC Agua 50 mmx300 cm',brand:'S',unit:'UNIDAD',cost:7090.0,baseQty:0.33,pres:'Tubo 3m'},
      {id:'POD_066',cat:'SANITARIO - ALCANTARILLADO',name:'COPLA PVC-S Bco 50mm',brand:'CONSTRUPLAZA',unit:'UNIDAD',cost:1100.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2134_65',cat:'SANITARIO - ALCANTARILLADO',name:'Abrazadera PVC-S 50mm Gris',brand:'S',unit:'UNIDAD',cost:720.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2176',cat:'SANITARIO - ALCANTARILLADO',name:'Tubo Blanco PVC Agua 40 mmx300 cm',brand:'S',unit:'UNIDAD',cost:5590.0,baseQty:0.33,pres:'Tubo 3m'},
      {id:'CRI2171',cat:'SANITARIO - ALCANTARILLADO',name:'Codo 87,5o PVC-S Bco c/goma 40mm Blanco',brand:'S',unit:'UNIDAD',cost:590.0,baseQty:2.0,pres:'Unidad'},
      {id:'CRI2138',cat:'SANITARIO - ALCANTARILLADO',name:'Abrazadera PVC-S 40mm Gris',brand:'S',unit:'UNIDAD',cost:742.0,baseQty:2.0,pres:'Unidad'},
      {id:'POD_071',cat:'SANITARIO - ALCANTARILLADO',name:'Copla PVC-S Bco 40mm',brand:'HOFFENS',unit:'UNIDAD',cost:1690.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_072',cat:'SANITARIO - ALCANTARILLADO',name:'Lubricante para tuberías 500 cc',brand:'S',unit:'UNIDAD',cost:2490.0,baseQty:0.1,pres:'Botella 500cc'},
      {id:'POD_073',cat:'SANITARIO - ALCANTARILLADO',name:'Tornillo 12-14 x 1 1/4¨cabeza hexagonal punta broca flange galvanizado  con g...',brand:'STEELFIX',unit:'UNIDAD',cost:30.0,baseQty:2.0,pres:'Unidad'},
      {id:'CSA148',cat:'SANITARIO',name:'Capuchón de goma 40 mm',brand:'S',unit:'UNIDAD',cost:1290.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_075',cat:'SANITARIO - ARTEFACTOS INSUMOS',name:'Teflón para gas 1/2\" 10 m',brand:'S',unit:'UNIDAD',cost:1890.0,baseQty:0.25,pres:'Rollo 10m'},
      {id:'POD_076',cat:'SANITARIO - ALCANTARILLADO',name:'ZOCALO SANITARIO BP-01 ACRILICO BLANCO - AISLADO',brand:'S',unit:'UNIDAD',cost:44600.0,baseQty:1.0,pres:'Unidad fabricada'},
      {id:'POD_077',cat:'SANITARIO - INSUMO',name:'Adhesivo PVC 237 ml Tradicional Profesional',brand:'S',unit:'UNIDAD',cost:4890.0,baseQty:0.25,pres:'Pote 237ml'},
      {id:'POD_078',cat:'ARTEFACTO BAÑO - INSUMOS',name:'Sello para tina PVC 25 mm',brand:'S',unit:'UNIDAD',cost:14990.0,baseQty:1.5,pres:'Tira'},
      {id:'POD_079',cat:'SANITARIO - INSUMO',name:'Silicona Acética Blanca con Fungicida Rex Cartucho 300 ml',brand:'S',unit:'UNIDAD',cost:4590.0,baseQty:1.0,pres:'Cartucho 300ml'},
      {id:'POD_080',cat:'SANITARIO - INSUMO',name:'Sellador acrílico 300 ml blanco',brand:'S',unit:'UNIDAD',cost:4590.0,baseQty:1.0,pres:'Cartucho 300ml'},
      {id:'POD_081',cat:'PANEL MURO',name:'YESOCARTÓN ST 12,5 MM 1200X2400MM',unit:'UNIDAD',cost:6106.0,baseQty:4.0,pres:'Plancha 1200x2400',revRole:'revST125'},
      {id:'CRI1916',cat:'PANEL MURO',name:'YESO CARTON RH 12,5mm 1200 X 2400mm',unit:'UNIDAD',cost:9134.0,baseQty:6.0,pres:'Plancha 1200x2400',revRole:'revRH125'},
      {id:'CRI1916_81',cat:'PANEL MURO',name:'YESO CARTON RF 12,5mm 1200 X 2400mm',unit:'UNIDAD',cost:9134.0,baseQty:4.0,pres:'Plancha 1200x2400',revRole:'revRF125'},
      {id:'CRI010',cat:'PANEL MURO',name:'YESOCARTÓN ST 10 MM 1200X2400MM',unit:'UNIDAD',cost:4176.0,baseQty:2.0,pres:'Plancha 1200x2400',revRole:'revST10'},
      {id:'POD_085',cat:'PANEL MURO',name:'FIBRO CEMENTO LISO 6mm 1200 X 2400mm',unit:'UNIDAD',cost:9134.0,baseQty:0.5,pres:'Plancha 1200x2400',revRole:'revFibro'},
      {id:'POD_086',cat:'PANEL MURO - INSUMO',name:'Espuma niveladora 3mm x 10m',brand:'S',unit:'UNIDAD',cost:11990.0,baseQty:0.2,pres:'Unidad'},
      {id:'POD_087',cat:'PANEL MURO - INSUMO',name:'Tornillo B-Phillips zincado punta broca 6 - 20 x 1 5/8¨ (000-171)',brand:'STEELFIX',unit:'UNIDAD',cost:5.4,baseQty:125.0,pres:'Unidad'},
      {id:'CRI1170',cat:'PANEL MURO - INSUMO',name:'Tornillo B-Phillips zincado punta broca 6 - 20 x 1 1/4¨ (000-168)',brand:'STEELFIX',unit:'UNIDAD',cost:5.4,baseQty:400.0,pres:'Unidad'},
      {id:'CRI306',cat:'PANEL MURO - INSUMO',name:'JuntaPro Volcan® 10cm x 45m',brand:'S',unit:'UNIDAD',cost:4228.0,baseQty:1.0,pres:'Rollo 45m'},
      {id:'CRI046',cat:'PANEL MURO - INSUMO',name:'Masilla base junta PRO 25 kg',brand:'S',unit:'UNIDAD',cost:20990.0,baseQty:0.5,pres:'Saco 25kg'},
      {id:'POD_091',cat:'TERMINACION MURO - INSUMO',name:'Pasta para muro de interior 25 kg',brand:'S',unit:'UNIDAD',cost:17900.0,baseQty:0.5,pres:'Saco 25kg',termGroup:'pintura'},
      {id:'POD_092',cat:'TERMINACION MURO - INSUMO',name:'CAVE POLFLEX - F BALDE 20 KG',brand:'CAVE',unit:'UNIDAD',cost:64600.0,baseQty:0.33,pres:'Balde 20kg'},
      {id:'POD_093',cat:'PANEL MURO - INSUMO',name:'dymonic FC blanco',brand:'CAVE',unit:'UNIDAD',cost:3150.0,baseQty:3.0,pres:'Cartucho'},
      {id:'POD_094',cat:'PANEL MURO - INSUMO',name:'dymonic FC gris',brand:'CAVE',unit:'UNIDAD',cost:3150.0,baseQty:1.0,pres:'Cartucho'},
      {id:'POD_095',cat:'PANEL MURO - INSUMO',name:'Aislanglass Rollo Papel 1C R100/94 40MM',brand:'VOLCAN',unit:'UNIDAD',cost:42399.0,baseQty:1.0,pres:'Rollo'},
      {id:'CRI2184',cat:'PANEL MURO - INSUMO',name:'VOLCAN WRAP BARRERA DE VAPOR',brand:'volcan',unit:'MT',cost:792.76,baseQty:2.0,pres:'Metro lineal'},
      {id:'CRI2185',cat:'PANEL MURO - INSUMO',name:'VOLCAN WRAP MURO',brand:'volcan',unit:'MT',cost:1086.12,baseQty:3.0,pres:'Metro lineal'},
      {id:'POD_098',cat:'PANEL MURO - INSUMO',name:'Cinta Construcción VolcanWrap 50,29 m',brand:'volcan',unit:'UNIDAD',cost:20090.0,baseQty:0.2,pres:'Rollo 50m'},
      {id:'POD_099',cat:'TERMINACION MURO - INSUMO',name:'Adhesivo cerámico BECKRON BLANCO INVIERNO A.C',unit:'UNIDAD',cost:10950.0,baseQty:2.5,pres:'Saco 25kg',termGroup:'ceramica'},
      {id:'POD_100',cat:'TERMINACION MURO - INSUMO',name:'Espaciador 2 mm con tomador',brand:'S',unit:'UNIDAD',cost:2290.0,baseQty:0.5,pres:'Unidad',termGroup:'ceramica'},
      {id:'CTE042',cat:'TERMINACION MURO - INSUMO',name:'Fragüe piso/muro blanco 5kg BECKRON',brand:'S',unit:'UNIDAD',cost:2290.0,baseQty:2.0,pres:'Saco 5kg',termGroup:'ceramica'},
      {id:'CRI1170_101',cat:'CIELO - INSUMO',name:'Tornillo B-Phillips zincado punta broca 6 - 20 x 1 1/4¨ (000-168)',brand:'STEELFIX',unit:'UNIDAD',cost:5.4,baseQty:100.0,pres:'Unidad'},
      {id:'BASE-CUARZ',cat:'BASE',name:'TX-Cuarz PRO (puente adherente 2 capas)',brand:'Grupo TX',unit:'UNIDAD',cost:55000.0,baseQty:0.07,pres:'Tineta 20kg'},
      {id:'BASE-MORTERO',cat:'BASE',name:'TX-Mortero Autonivelante con Fibra (saco 25kg)',brand:'Grupo TX',unit:'UNIDAD',cost:10140.0,baseQty:2.53,pres:'Saco 25kg'},
      {id:'CRI1216',cat:'PANEL MURO - INSUMO',name:'ILLBRUCK FM 310 ESPUMA DE POLIURETANO',brand:'CAVE',unit:'UNIDAD',cost:3050.0,baseQty:0.5,pres:'Lata'},
      {id:'CRI1214',cat:'TERMINACION CIELO - INSUMO',name:'ILLBRUCK PU010 ESPUMA ADHESIVA Lata 750ml',brand:'CAVE',unit:'UNIDAD',cost:6800.0,baseQty:0.5,pres:'Lata 750ml'},
      {id:'CRI1215',cat:'TERMINACION CIELO - INSUMO',name:'ILLBRUCK AA290 LIMPIADOR MILTIUSOS',brand:'CAVE',unit:'UNIDAD',cost:1220.0,baseQty:0.25,pres:'Botella'},
      {id:'CRI1299',cat:'TERMINACION CIELO - INSUMO',name:'ILLBRUCK Boquillas AA 210',brand:'CAVE',unit:'UNIDAD',cost:437.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_110',cat:'INSUMOS GENERALES',name:'RODILLO DE PUAS',unit:'UNIDAD',cost:81900.0,baseQty:0.02,pres:'Unidad'},
      {id:'POD_111',cat:'INSUMOS GENERALES',name:'Pintura en Spray Amarillo Fiesta 400ml',brand:'S',unit:'UNIDAD',cost:7000.0,baseQty:0.15,pres:'Spray 400ml'},
      {id:'POD_112',cat:'INSUMOS GENERALES',name:'Cinta Aisladora Eléctrica Alto Desempeño 19 mm x 9 m Negra',brand:'S',unit:'UNIDAD',cost:1990.0,baseQty:0.5,pres:'Rollo 9m'},
      {id:'POD_113',cat:'INSUMOS GENERALES',name:'Cinta Aisladora Eléctrica Alto Desempeño 19 mm x 9 m ROJO',brand:'S',unit:'UNIDAD',cost:2388.0,baseQty:0.14,pres:'Rollo 9m'},
      {id:'POD_114',cat:'INSUMOS GENERALES',name:'Cinta Aisladora Eléctrica Alto Desempeño 19 mm x 9 m AZUL',brand:'S',unit:'UNIDAD',cost:2388.0,baseQty:0.14,pres:'Rollo 9m'},
      {id:'POD_115',cat:'INSUMOS GENERALES',name:'Cinta Aisladora Eléctrica Alto Desempeño 19 mm x 9 m VERDE',brand:'S',unit:'UNIDAD',cost:2388.0,baseQty:0.14,pres:'Rollo 9m'},
      {id:'POD_116',cat:'INSUMOS GENERALES',name:'Cinta Aisladora Eléctrica Alto Desempeño 19 mm x 9 m BLANCO',brand:'S',unit:'UNIDAD',cost:2388.0,baseQty:0.14,pres:'Rollo 9m'},
      {id:'POD_117',cat:'INSUMOS GENERALES',name:'Cinta para enmascarar 48 mm 40 m',brand:'S',unit:'UNIDAD',cost:2090.0,baseQty:2.0,pres:'Rollo 40m'},
      {id:'POD_118',cat:'EMBALAJE',name:'ROLLO FILM STRETCH NAT USO MANUAL 50*20',unit:'UNIDAD',cost:24489.0,baseQty:1.0,pres:'Rollo'},
      {id:'POD_119',cat:'EMBALAJE',name:'Polietileno negro 4x25 m standard',unit:'UNIDAD',cost:4750.0,baseQty:0.5,pres:'Rollo 4x25m'},
      {id:'POD_120',cat:'EMBALAJE',name:'Cinta Adhesiva para embalaje transparente 48 mm x 40 mts',brand:'S',unit:'UNIDAD',cost:1690.0,baseQty:1.0,pres:'Rollo 40m'},
      {id:'POD_121',cat:'ARTEFACTO BAÑO',name:'Tina con Antideslizante 70x130 cm Rectangular Acero Esmaltado',brand:'FANALOZA',unit:'UNIDAD',cost:92990.0,baseQty:1.0,pres:'Unidad',slot:'tina'},
      {id:'POD_122',cat:'ARTEFACTO BAÑO',name:'Desague Tina Plástico 1 1/2\" c/Rebalse c/Sifón HOFFENS',brand:'S',unit:'UNIDAD',cost:8190.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_123',cat:'ARTEFACTO BAÑO',name:'Sifón PVC 1 1/4\" 66 cm',brand:'FANALOZA',unit:'UNIDAD',cost:4880.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_124',cat:'ARTEFACTO BAÑO',name:'SOPORTE DE TINA STANDARD D25 H13',brand:'FANALOZA',unit:'UNIDAD',cost:12650.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_125',cat:'ARTEFACTO BAÑO',name:'Celosía Ventilación 30x30cm Nova Clip Blanco',brand:'DVP',unit:'UNIDAD',cost:12650.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_126',cat:'ARTEFACTO BAÑO',name:'LAVAMANOS NEW VERONA 5 LT BLANCO',brand:'FANALOZA',unit:'UNIDAD',cost:16200.0,baseQty:1.0,pres:'Unidad',slot:'lavamanos'},
      {id:'POD_127',cat:'ARTEFACTO BAÑO',name:'PEDESTAL UNIVERSAL BLANCO',brand:'FANALOZA',unit:'UNIDAD',cost:12410.0,baseQty:1.0,pres:'Unidad',slot:'pedestal'},
      {id:'POD_128',cat:'ARTEFACTO BAÑO',name:'KIT INSTALACION LAVAMANOS UNIVERSAL',brand:'FANALOZA',unit:'UNIDAD',cost:7870.0,baseQty:1.0,pres:'Kit'},
      {id:'CSA032',cat:'ARTEFACTO BAÑO',name:'UÑETA LARGA DE ACERO PARA LAVAMANOS',brand:'S',unit:'UNIDAD',cost:1779.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_130',cat:'ARTEFACTO BAÑO',name:'SS.\' Krone-N tanque sin mecanismo, Bath Co',brand:'CHC',unit:'UNIDAD',cost:24614.0,baseQty:1.0,pres:'Unidad',slot:'wc_tanque'},
      {id:'POD_131',cat:'ARTEFACTO BAÑO',name:'SS.\' Krone-N taza WC salida dual sin fijacion, Bath Co.',brand:'CHC',unit:'UNIDAD',cost:24614.0,baseQty:1.0,pres:'Unidad',slot:'wc_taza'},
      {id:'POD_132',cat:'ARTEFACTO BAÑO',name:'SS.\' Akim, Krone, Krone-N, Lofty y Magnet asiento y tapa plastica instal. su...',brand:'CHC',unit:'UNIDAD',cost:7866.0,baseQty:1.0,pres:'Unidad',slot:'wc_asiento'},
      {id:'POD_133',cat:'ARTEFACTO BAÑO',name:'SS.\' Krone y Krone-N Inc. en tanque, mecanismo completo y fijacion al piso',brand:'CHC',unit:'UNIDAD',cost:189.0,baseQty:1.0,pres:'Kit'},
      {id:'POD_134',cat:'ARTEFACTO BAÑO',name:'KIT INSTALACIÓN WC MURO (CON FLEX 30CM)',brand:'FANALOZA',unit:'UNIDAD',cost:5240.0,baseQty:1.0,pres:'Kit'},
      {id:'POD_135',cat:'ARTEFACTO BAÑO',name:'MM LAVAMANOS ANDES CROMADO',brand:'FANALOZA',unit:'UNIDAD',cost:11950.0,baseQty:1.0,pres:'Unidad',slot:'grif_lav'},
      {id:'POD_136',cat:'ARTEFACTO BAÑO',name:'MM TINA DUCHA ANDES CROMADO',brand:'FANALOZA',unit:'UNIDAD',cost:21480.0,baseQty:1.0,pres:'Unidad',slot:'grif_tina'},
      {id:'POD_137',cat:'ARTEFACTO BAÑO',name:'Extractor Baño Reton 100 BTH',brand:'JONAS',unit:'UNIDAD',cost:49990.0,baseQty:1.0,pres:'Unidad',slot:'extractor'},
      {id:'POD_138',cat:'TERMINACION PISO',pisoGroup:'ceramica',name:'Cerámica 30x30 cm America blanco caja 2,34 mt2',brand:'I',unit:'UNIDAD',cost:17590.0,baseQty:4.0,pres:'Caja 2,34m²'},
      {id:'POD_139',cat:'TERMINACION MURO',name:'Esquinero cerámico 8 mm 2,5 m',brand:'S',unit:'UNIDAD',cost:9990.0,baseQty:2.0,pres:'Tira 2,5m',termGroup:'ceramica'},
      {id:'POD_140',cat:'TERMINACION MURO',name:'Guardapolvo EPS Recto Blanco 1,3x8x220 cm',brand:'AB KÜPFER',unit:'UNIDAD',cost:3570.0,baseQty:1.0,pres:'Tira 220cm'},
      {id:'POD_141',cat:'TERMINACION MURO',name:'Molduras poliestireno extruido LX25',brand:'S',unit:'UNIDAD',cost:2190.0,baseQty:5.0,pres:'Tira'},
      {id:'POD_142',cat:'TERMINACION MURO',name:'LATEX SKT BLANCO (TINA 4GL)',brand:'S',unit:'UNIDAD',cost:69159.0,baseQty:0.25,pres:'Tineta 4GL',termGroup:'pintura_latex'},
      {id:'POD_143',cat:'TERMINACION MURO',name:'ESMALTE AL AGUA EAA RL KP CONSTRUCCION SATIN BCO (TIP 5GL)',brand:'S',unit:'UNIDAD',cost:72900.0,baseQty:0.2,pres:'Tineta 5GL',termGroup:'pintura_esmalte'},
      {id:'POD_144',cat:'PUERTAS',slot:'puerta',name:'PUERTA PRECOLGADA HOJA 700mm, PREPINTADA COLOR BLANCO, MARCO 30X90X2000 CON C...',brand:'S',unit:'UNIDAD',cost:50000.0,baseQty:1.0,pres:'Unidad precolgada'},
      {id:'POD_145',cat:'PUERTAS',slot:'cerradura',name:'Cerradura Cilíndrica Odis 201 BAÑO - Plata',brand:'S',unit:'UNIDAD',cost:13990.0,baseQty:1.0,pres:'Unidad'},
      {id:'POD_146',cat:'PUERTAS',name:'Tope de puerta recto Níquel satinado Särk Design',brand:'S',unit:'UNIDAD',cost:3990.0,baseQty:1.0,pres:'Unidad'},
      {id:'CRI521',cat:'PUERTAS - INSUMO',name:'TORNILLO B-PHILLIPS ZINCADO PUNTA BROCA 8-18 x 3\"',brand:'STEELFIX',unit:'UNIDAD',cost:55.22,baseQty:55.0,pres:'Unidad'},
      {id:'POD_148',cat:'TERMINACION BASE - INSUMO',name:'PIntura epoxica 2 compuestos 1GL',brand:'TRICOLOR',unit:'UNIDAD',cost:40072.0,baseQty:0.17,pres:'Galón'},
      {id:'POD_149',cat:'TERMINACION BASE - INSUMO',name:'diluyente Epoxico passol 1 lt',brand:'TRICOLOR',unit:'UNIDAD',cost:3350.0,baseQty:1.0,pres:'Botella 1L'},
      {id:'POD_150',cat:'TERMINACION BASE - INSUMO',name:'Detergente desengrasante Bd 5L DEGVAL',brand:'TRICOLOR',unit:'UNIDAD',cost:8970.0,baseQty:0.25,pres:'Bidón 5L'},
      {id:'POD_151',cat:'INSUMOS GENERALES',name:'Tornillo B-Phillips zincado punta fina 6 - 18 x 1 1/4¨',brand:'TRICOLOR',unit:'UNIDAD',cost:50.0,baseQty:10.0,pres:'Unidad'},
      {id:'POD_152',cat:'INSUMOS GENERALES',name:'ADHESIVO ESTRUCTURAL Y TAPAGOTERAS GRIS 280 ML (TODO EN 1)',brand:'Mr. build',unit:'UNIDAD',cost:3400.0,baseQty:0.33,pres:'Cartucho 280ml'},
      {id:'POD_153',cat:'INSUMOS GENERALES',name:'Tarugo de nylon 5 mm 100 unidades',brand:'Mr. build',unit:'UNIDAD',cost:3400.0,baseQty:0.09,pres:'Bolsa 100un'},
      {id:'POD_154',cat:'INSUMOS GENERALES',name:'Golilla Plana Zincada 1/4 (100 Unidades)',brand:'S',unit:'UNIDAD',cost:6890.0,baseQty:0.04,pres:'Bolsa 100un'}
];
